# Generated by Django 4.1.5 on 2023-01-26 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_image_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.image'),
        ),
    ]
