# Generated by Django 4.1.5 on 2023-01-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_image_product_image_id_image_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_id',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
