# Generated by Django 4.1.5 on 2023-01-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_orderproduct_order_id_orderproduct_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order_id',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order_id',
            field=models.ManyToManyField(to='order.order'),
        ),
    ]
