# Generated by Django 4.1.5 on 2023-01-30 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_orderproduct_order_id_orderproduct_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order_id',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
